#ifndef CONFIG_H
#define CONFIG_H

// Serial
#define SERIAL_BAUD_RATE 115200

// DHT11
#define DHT_PIN 4
#define DHT_TYPE DHT11

// SGP30
#define SGP30_SDA 18
#define SGP30_SCL 19
#define SGP30_I2C_ADDRESS 0x58

// Sensors
#define SOIL_MOISTURE_PIN 34
#define RAIN_SENSOR_PIN 13
#define DS18B20_PIN_1 5
#define DS18B20_PIN_2 21
#define DS18B20_ADDRESS 0x28
#define PIR_PIN 12
#define LIGHT_SENSOR_PIN 32

// LEDs
#define BUILTIN_LED_PIN 2
#define RGB_RED_PIN 25
#define RGB_GREEN_PIN 26
#define RGB_BLUE_PIN -1

// PWM
#define LEDC_CHANNEL_RED 0
#define LEDC_CHANNEL_GREEN 1
#define LEDC_FREQUENCY 5000
#define LEDC_RESOLUTION 8

#define BRIGHTNESS_RED 255
#define BRIGHTNESS_GREEN 255
#define BRIGHTNESS_YELLOW_RED 255
#define BRIGHTNESS_YELLOW_GREEN 50

// System
#define SENSOR_READ_INTERVAL 2000
#define I2C_SCAN_ENABLED false

// Wi-Fi
#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define WIFI_CONNECT_TIMEOUT 10000
#define WIFI_RETRY_INTERVAL 5000
#define MAX_RETRY_COUNT 5

// Gateway server
#define GATEWAY_ID "esp-gateway-001"
#define GATEWAY_NAME "ESP32 Gateway"
#define GATEWAY_LOCATION "North Greenhouse"
#define GATEWAY_PORT 8080
#define GATEWAY_WS_PATH "/ws"
#define GATEWAY_FIRMWARE_VERSION "1.2.0"

// Transport behavior
#define TELEMETRY_PUSH_INTERVAL_MS 2000
#define HEARTBEAT_INTERVAL_MS 15000
#define COMMAND_IDEMPOTENT_WINDOW_MS 30000
#define MAX_COMMAND_HISTORY 12
#define MAX_WS_CLIENTS 8

// Actuator defaults
#define DEFAULT_GROW_LIGHT_LEVEL 3
#define DEFAULT_PUMP_DURATION_SEC 30
#define MAX_PUMP_DURATION_SEC 600

#endif
